remove positive number validation for getRow ind.
NeurodataWithoutBorders/matnwb pull request #311
Opened 2021-09-29 14:12 UTC by bendichter

fix #310 

If useID is True, then ind can be of value 0

2021-09-29 15:08 UTC, ln-vidrio requested changes
Since `ind` isn't used until `useId` is checked for on line 29, I would like to still check that the index is within a valid range if  `useId` is *not* set. Something like:

```MATLAB
if p.Results.useId
    validateattributes(ind, {'numeric'}, {'vector'});
    ind = getIndById(DynamicTable, ind);
else
    validateattributes(ind, {'numeric'}, {'positive', 'vector'});
end
```

2021-09-29 15:26 UTC, bendichter commented
@ln-vidrio that sounds fine

2024-06-24 16:29 UTC, lawrence-mbf commented
pipeline failure allowable as that should be resolved by #575

2024-06-24 16:30 UTC, lawrence-mbf approved these changes

2024-06-24 16:39 UTC, merged