create utility function to load spike times data aligned to a particular event
NeurodataWithoutBorders/matnwb pull request #374
Opened 2022-01-03 17:56 UTC by cechava

this PR creates a utility function to load event-aligned spike time data similar to loadTrialAlignedTimeSeriesData utility function.

sample usage:
```matlab
DANDIset_folder = '~/DANDIsets/000017/';
filepath = [DANDIset_folder 'sub-Moniz/sub-Moniz_ses-20170515T120000.nwb'];
% read in file
nwb_file = nwbRead(filepath);
% get stimulus-aligned spike data
psth_data = util.loadEventAlignedSpikeTimes( nwb_file, 5, ...
    'before_time', 1, ...
    'after_time', 1, ...
    'align_to', 'visual_stimulus_time' ...
);
```

2022-01-04 23:37 UTC, cechava commented
@bendichter just want to make sure this didn't get lost in your inbox. Let me know your thoughts.

2022-01-05 00:31 UTC, bendichter commented on +util/loadEventAlignedSpikeTimes.m
> +addOptional(p,'align_to',defaultAlign,validAlign);
```suggestion
% Define anonymous functions to check input
validNWB = @(x) isa(x,'types.core.NWBFile');
validUnit = @(x) isscalar(x);
validTime = @(x) isnumeric(x) && (x>=0);
validAlign = @(x) ischar(x);
% Define parser with arguments
p = inputParser;
addRequired(p, 'nwb', validNWB);
addRequired(p, 'unit_id', validUnit);
addOptional(p, 'before_time', 1., validTime);
addOptional(p, 'after_time' ,1., validTime);
addOptional(p, 'align_to', 'start_time');
```
I think this is clear enough

2022-01-05 00:31 UTC, bendichter commented on +util/loadEventAlignedSpikeTimes.m
> +                                       unit_id);
Didn't we decide to deprecate this? Can you do this with `getRow`?

2022-01-05 00:32 UTC, bendichter commented on +util/loadEventAlignedSpikeTimes.m
> +                       ref_time;
```suggestion
                       ref_time);
```

2022-01-05 00:33 UTC, bendichter commented on +util/loadEventAlignedSpikeTimes.m
> +%   aligns data to the column named ALIGN_TO. Default is 'start_time'.
Let's use key-value pairs. I used position for the other function but I think that was a mistake

2022-01-05 00:34 UTC, bendichter commented on +util/loadEventAlignedSpikeTimes.m
> +%   aligns data to the column named ALIGN_TO. Default is 'start_time'.
I guess you are using key-value pairs, but this comment block looks like it's not

2022-01-05 16:14 UTC, cechava commented on +util/loadEventAlignedSpikeTimes.m
> +                                       unit_id);
yes, this can be done with getRow. I forgot we decided to deprecate. We never got around to it. I can start a PR to do a gentle deprecation of this function.

2022-01-05 16:56 UTC, bendichter commented on +util/loadEventAlignedSpikeTimes.m
> +%   to align spike times
```suggestion
%   to align spike times. Default is 'start_time'.
```

2022-01-05 16:56 UTC, bendichter commented on +util/loadEventAlignedSpikeTimes.m
> +% Define default values
```suggestion
```

2022-01-05 16:57 UTC, bendichter commented on +util/loadEventAlignedSpikeTimes.m
> +parse(p,nwb,unit_id,varargin{:});
```suggestion
parse(p, nwb, unit_id,varargin{:});
```

2022-01-05 16:57 UTC, bendichter commented on +util/loadEventAlignedSpikeTimes.m
> +    'columns',{'spike_times'} ...
```suggestion
    'columns', {'spike_times'} ...
```

2022-01-05 16:58 UTC, bendichter approved these changes

2022-01-05 17:00 UTC, bendichter requested changes
loadEventAlignedSpikeTimes should take as input the events. For automatically aligning to trials, the function should be loadTrialAlignedSpikeTimes.

2022-01-05 17:23 UTC, cechava commented
> loadEventAlignedSpikeTimes should take as input the events. For automatically aligning to trials, the function should be loadTrialAlignedSpikeTimes.

will do

2022-01-06 16:34 UTC, bendichter commented
@cechava looks great! Can you please add some tests as well?

2022-01-06 22:31 UTC, cechava commented
@bendichter
I've added the tests

2022-01-06 22:41 UTC, bendichter approved these changes

2022-01-06 22:41 UTC, bendichter commented
Looks great!

2022-01-06 22:48 UTC, merged